### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by tarpdalton** [vjeantet/hugo-theme-docdock#102]
Is there any interest is switching from [highlight.js](https://highlightjs.org/) (client side highlighting) to [chroma](https://github.com/alecthomas/chroma) (hugo's built in syntax highlighter)? 
Info from the hugo docs: https://gohugo.io/content-management/syntax-highlighting/ 

Pros
- Faster client side site rendering
- One less js file

Cons
- I'm worried it could cause problems with mermaid.js
- Could be a breaking change for anyone with custom CSS on their code snippets.

**Comment by vjeantet** [comment]
Yes there is, highlight.js is about 500kb ;-(

You could make a PR ?

**Comment by tarpdalton** [comment]
Yeah I’ll try to start working on it. I just didn’t want to start if it wasn’t wanted/needed

**Comment by vjeantet** [comment]
Cool

**Comment by tarpdalton** [comment]
It looks like adding `pygmentsCodeFences = true` to config.toml, or using the [highlight shortcode](https://gohugo.io/content-management/shortcodes/#highlight) will use chroma for syntax highlighting. So I think it is a matter of removing the highlight.js file and the css.

**Comment by xxxtonixxx** [comment]
Could it be optional? I would like to have the option of use chrome or highlight

**Comment by tarpdalton** [comment]
A hacky way to switch to chroma is to add an empty file at `/static/js/highlight.pack.js` and add `pygmentsCodeFences = true` to config.toml (if you're using backticks for code blocks).

It loads a little faster, but is not a good solution since it still tries to reference highlight.js.
I'll have to look into making it an option in the config, and making sure hugo doesn't load/reference the unneeded resources.

**Comment by DaddyOh** [comment]
I'd like to have the choice for either chroma or highlight.js.  Thanks for considering this change.
