### ISSUE TITLE
Where to translate the shortcode warning?

### ISSUE THREAD

**Issue by mdosch** [vjeantet/hugo-theme-docdock#103]
I created a warning in my website by using this: 

`{{% notice warning %}}
something something{{% /notice %}}
`
In the compiled website beside the `!` there is written `Warning` but as the target audience is german I wanted to change this to `Warnung`. I was grepping through the theme and copying the css and scss files to ./static and tried to get the string translated but to no avail. 

So please tell me which file I need to copy to ./static and edit to get this string changed as I am clueless right now.

**Comment by vjeantet** [comment]
Hello,

in your content folder, create a `layout/partials/curstom-head.html` file.
This file will be inserted in the head part of each page.

in this file just add :
```html
<style type="text/css">
div.notices.warning p:first-child:after {  content: 'Warnung'; }
</style>
```

**Comment by mdosch** [comment]
Hi,
it works. Thank you.
But it's custom not curstom, of course.

Am January 14, 2018 2:23:20 PM UTC schrieb Valere JEANTET <notifications@github.com>:
