### ISSUE TITLE
Do version releases on braking and major changes

### ISSUE THREAD

**Issue by Pilskalns** [vjeantet/hugo-theme-docdock#104]
Just pulled changes made in few last months and broke few things with custom layouts/styles/color schemes relying on the previous state. Good that I keep a private fork and could track changes since then needed to adjust.

There should be releases on such occasions, especially if dependencies change (Hugo version). This is more suggestion rather than an immediate issue.

**Comment by vjeantet** [comment]
Good suggestion. I’ll try to do more semversionning
