### ISSUE TITLE
Menu on mobile devices

### ISSUE THREAD

**Issue by jmburgos** [vjeantet/hugo-theme-docdock#11]
Hello,
Sorry if this is a basic question.  I'm using your theme and I am having some issue with displaying the menu on mobile devices.  If I open your page,

http://docdock.netlify.com/

The menu button appears on the top left on the screen.  On my site, on the other hand, the menu button does not appears.

http://novasarc.hafogvatn.is//

How do you enable the menu on mobile devices?

Many thanks,

Julian

**Comment by vjeantet** [comment]
Hello, I will fix it tonight.

Workaround : put this HTML code in the first lines of your index_md

```
<span id="sidebar-toggle-span">
<a href="#" id="sidebar-toggle" data-sidebar-toggle=""><i class="fa fa-bars"></i></a>
</span>
```

**Comment by vjeantet** [comment]
_index.md

**Comment by tarpdalton** [comment]
This worked for me, but when selecting the header menu on mobile there isnt a way to exit the header menu after you have selected a header

**Comment by tarpdalton** [comment]
It might be useful to just have the header menu hide after an anchor link is clicked
