### ISSUE TITLE
Search problems

### ISSUE THREAD

**Issue by TimotheClavier** [vjeantet/hugo-theme-docdock#12]
Hi !

I don't understand why my search bar just highlights some words. I installed lunr et i tried a lot of solution but nothing help me ! 

maybe my index is wrong but lunr do it automaticaly

Can you help me please ? (forgive my english, i learn ;) )

**Comment by vjeantet** [comment]
Salut Timo,

  Can you share your repo to investigate ?

**Comment by TimotheClavier** [comment]
its a bit longer ^^
the file was to heavy for the site
i delete my npm adds and i send you this

**Comment by TimotheClavier** [comment]
https://github.com/TimotheClavier/metiwiki.git

Thats the meti.zip file
i want to say i'm under a proxy in my enterprise and i can't do a git clone so i downloaded the zip and i put him in my theme folder.
I don't know if this has an importance but i prefer say it

Thanks !!

**Comment by TimotheClavier** [comment]
Hum sorry but my index don't take all of my content, juste 29 on 80

You know somethings about this ?

**Comment by cmrust** [comment]
I ran into the same problem as @TimotheClavier. The `baseURL` value in my `config.toml` file was pointed to the wrong environment. Without this, the search functionality fails to pull in the index.json and instead only highlights the results that appear on that page.
