### ISSUE TITLE
Meaning of "Clear History" ?

### ISSUE THREAD

**Issue by mdavids** [vjeantet/hugo-theme-docdock#121]
In [Matcornic Learn theme](https://github.com/matcornic/hugo-theme-learn/) the "Clear history" option removes the ticks that are set behind visited sections. I don't see such ticks in hugo-theme-docdock and was wondering if the "Clear history" makes any sense in docdock.

**Comment by vjeantet** [comment]
This is used in the original theme.

In docdock you can choose which style to use between « original » and « flex »

Original style use this parameter
