### ISSUE TITLE
Image resize no longer working

### ISSUE THREAD

**Issue by mdosch** [vjeantet/hugo-theme-docdock#128]
I just updated docdock and I realized that image resizing doesn't work anymore (see: https://xmpp.mdosch.de/apps/conversations/ ) also I haven't change anything with my source files. Also according to your documentation this function is still available: http://docdock.netlify.com/create-page/page-images/

**Comment by tarpdalton** [comment]
I'm not why it stopped working in the theme, but Hugo introduced its own [image processing in 0.32](https://gohugo.io/about/new-in-032/#image-processing), so maybe that will work better?

**Comment by mdosch** [comment]
I couldn't figure out how this integrated stuff works. But as I updated the submodules it's working again so it seems you fixed it upstream.
