### ISSUE TITLE
Option to apply GitHub flavored markdown to process md files

### ISSUE THREAD

**Issue by jsrakesh4** [vjeantet/hugo-theme-docdock#131]
I would like to know if there is a way to apply GitHub flavored markdown when building in Hugo with docdock theme. Thanks in advance

My website has bunch of anchors to different sections in a page. After building with Hugo and docdock theme they are not working.

Example: 

```
1. [heading_1](#heading1)
2. [CPU%Too_High](#cputoohigh)
3. [Third Heading](#third-heading)
```
After building the site the anchors are created as below.

```
#heading-1
#cpu-too-high
#third-heading

**Comment by Pilskalns** [comment]
Hi @jsrakesh4,

HTML specifics is rendered by Hugo not by theme, which uses Blackfriday, I think. Not sure if there is way to configure this, but you have to look at those docs.

I am closing this issue :)
