### ISSUE TITLE
[Workaround/Solved] 0.40.1 breaks shortcode children

### ISSUE THREAD

**Issue by divinerites** [vjeantet/hugo-theme-docdock#142]
See https://discourse.gohugo.io/t/0-40-1-breaks-children-shortcode-from-docdock-theme/11737

I found nothing strange ... but just in case.
Do you see the same breakage @vjeantet ??

**Comment by divinerites** [comment]
In fact my analysis was wrong i think. It is a reload logic/build problem.

See https://discourse.gohugo.io/t/the-live-reload-does-unconsistent-work/11770

**Comment by divinerites** [comment]
Well, the problem is not gone, and even worse with 0.40.2 : https://discourse.gohugo.io/t/the-live-reload-does-unconsistent-work/11770/4

**Comment by divinerites** [comment]
Shorter version for the problem:

{{ .Page.Pages }} behaves differently in the 2 Hugo versions

**Comment by divinerites** [comment]
@vjeantet, I've got Bep response (https://github.com/gohugoio/hugo/issues/4689#issuecomment-386908398) and it seems that `children` as writen for the moment will be broken starting with hugo 0.40 and later versions.

I'll try to look at the code to see if I can correct it (but really low level chances I guess).

**Comment by bmansheim** [comment]
@vjeantet What are the chances that this will be fixed?

The closest we have to a suggestion is "Note that the home page is special in this case. $home.Pages will be the “site’s pages”. So for the home page you may check that eq .Parent $home or something. I’m sure someone else will come up with something better …" https://discourse.gohugo.io/t/the-live-reload-does-inconsistent-work/11770/7

**Comment by bmansheim** [comment]
This is good enough for my purposes...
```
<ul class="children children-{{$style}}">
	{{- .Scratch.Set "pages" $cpage.Pages }}
	{{- if $cpage.Sections}}
	    {{- .Scratch.Set "pages" ($cpage.Sections) }}
        {{- end}}
    {{- $pages := (.Scratch.Get "pages") }}
```

**Comment by Pilskalns** [comment]
Hey @divinerites, @bmansheim 

Could you please elaborate the sample above, is the fix changing just one line? Is this backwards compatible?

**Comment by divinerites** [comment]
I changed accordingly with the code published above and never looked back.
I upgrade every Hugo version.
