### ISSUE TITLE
With themeStyle = "original" code & copy-to-clipboard icon is broken

### ISSUE THREAD

**Issue by petzi53** [vjeantet/hugo-theme-docdock#152]
After changing to themeStyle = "original" code snippets & copy-to-clipboard icon do not appear correctly.  

See for instance: [https://weblog-docdock.netlify.com/content-organisation/extramenu/](https://weblog-docdock.netlify.com/content-organisation/extramenu/)

It used to work with a previous version: See [here](https://notes.peter-baumgartner.net/archive/content-organisation/extramenu/)

**Comment by Pilskalns** [comment]
Hi @petzi53,

Thanks for noticing. I have this already fixed in my private fork, will push to master soon.
