### ISSUE TITLE
Wrong images with BaseUrl and subdirectory

### ISSUE THREAD

**Issue by morph027** [vjeantet/hugo-theme-docdock#16]
Somehow looks like https://github.com/vjeantet/hugo-theme-casper/issues/15

I do have `baseURL = "https://my.gitlab-pages.io/some-folder/"` and a image on a page is referenced with `https://my.gitlab-pages.io/images/image.svg` instead of `https://my.gitlab-pages.io/some-folder/images/image.svg`

By the way, thanks for this great theme :heart:

**Comment by morph027** [comment]
Right now, i'm doing this to have it working ;)

```bash
sed -i 's,/images,/some-foler/images,g' public/**/*.html
```

Which at least works within my Gitlab Pages job for now.

**Comment by vjeantet** [comment]
Hello @morph027 i can not reproduce your issue, i try with `baseURL = "http://localhost:1313/test/"`

can you provide me a link to your repo ?

**Comment by morph027** [comment]
Hm, just added a trailing slash to `baseURL` and it look like it's working.
