### ISSUE TITLE
issues building doc since Hugo v0.50

### ISSUE THREAD

**Issue by i4o** [vjeantet/hugo-theme-docdock#166]
Multiple identical error messages:
error calling partial: "/builds/dev/doc/themes/hugo-theme-docdock/layouts/partials/header.html:2:10": execute of template failed: template: partials/header.html:2:10: executing "partials/header.html" at <where .Site.Pages "S...>: error calling where: Source isn't a field of struct type *hugolib.Page

**Comment by i4o** [comment]
Just for refenece,this is how header.html looks like:

**Comment by divinerites** [comment]
If you do `  {{ range .Site.Pages }}` it will build without error. Obviously it looks weird 😄 but it build without error.

I guess there is some syntax checking change for `range where` ...

**Comment by divinerites** [comment]
and if you do exactly the same thing but with an index,  there is only one (same origin) error. Just one.

`{{ range $i, $value := where .Site.RegularPages "Source.BaseFileName" $header }}`

**Comment by divinerites** [comment]
Mmmmm seems they changed the Page variable somehow ...

`{{ range where .Site.Pages ".File.BaseFileName" $header }}` seems to solve the problem. I have to really check but seems ok. Let me know how it works on your side.

`Source` is really badly documented and I guess not for use in code.

**Comment by jjhamer** [comment]
Looks like Source was removed in 0.50
https://github.com/gohugoio/hugo/commit/7930d2132a3c36c1aaca20f16f56978c84656b0a

**Comment by pauby** [comment]
I had to replace `{{ range where .Site.Pages "Source.BaseFileName" $footer }}` with `{{ range where .Site.Pages ".File.BaseFileName" $footer }}` as well has in header.html

Can we get an update out with these fixes asap?

**Comment by divinerites** [comment]
> I had to replace `{{ range where .Site.Pages "Source.BaseFileName" $footer }}` with `{{ range where .Site.Pages ".File.BaseFileName" $footer }}` as well has in header.html
> 
> Can we get an update out with these fixes asap?

We already have submit PR for those fix.

See https://github.com/vjeantet/hugo-theme-docdock/pull/167 & #168 168

**Comment by pauby** [comment]
Awesome. Hopefully they will get pulled in and released asap.

**Comment by Pilskalns** [comment]
Hi,

I will test the changes with different Hugo versions and if everything fine, then will merge in PR this evening.

**Comment by Pilskalns** [comment]
This is fixed with #168 and backwards compatible.

Tested with hugo-extended `v0.49.2`, `v0.50` and `v0.51`
