### ISSUE TITLE
Images Shortcodes do not seem to influence image size examples.

### ISSUE THREAD

**Issue by zivbk1** [vjeantet/hugo-theme-docdock#17]
On this page: https://themes.gohugo.io/theme/docdock/shortcodes/image/

This code is not making the image show as 80px in height.

`![Hackathon](https://github.com/vjeantet/vjeantet.fr/raw/master/static/images/sgthon/C.jpg?height=80px)`

![2017-06-14_14-12-39](https://user-images.githubusercontent.com/6154767/27154890-8f0ffada-510b-11e7-9d09-567bb8f1eb80.png)

**Comment by vjeantet** [comment]
Good catch, I'll fix that

**Comment by zivbk1** [comment]
I really like the system/theme. Thank you for putting it together.

**Comment by vjeantet** [comment]
fixed
