### ISSUE TITLE
Support "prev" and "next" link tags in head

### ISSUE THREAD

**Issue by IsaacSchemm** [vjeantet/hugo-theme-docdock#171]
Link tags in the &lt;head> section with rel="next" and rel="prev" can be used to show how pages are related. [Google uses this](https://webmasters.googleblog.com/2011/09/pagination-with-relnext-and-relprev.html) to help with giving the most relevant search result. They're also supported in the SeaMonkey browser's website navigation toolbar. Since this theme handles navigation and is aware of previous/next relationships, it would be nice if the theme could insert these tags too.

There are also some other properties (rel="top", rel="up", rel="first", rel="last") that SeaMonkey supports, but I don't think anyone else uses them anymore.

**Comment by Pilskalns** [comment]
Hi @IsaacSchemm,

Nice idea, although I am concerned how it should be implemented or even if it should be at all.

From the Google guide "to indicate the relationship between component URLs in a **paginated** series."

AFAIK from my quick research, this feature is to show proper relation between **subset** of the same content. Like pieces of the same the cake should be linked together with next/prev piece. But each whole article is a cake on it's own.

In real world good examples, [the instructables](https://www.instructables.com/) have very long articles where you can page-by-page click it over, but you have also one single view-it-all page link.


In the end, if we chain all pages together with rel next/prev, then Google and other html meta consumers will think that **whole** site is one single article sliced into the pieces, which is not really intended.

_P.S. To ease out navigation for user, I would rather consider adding keyboard shortcuts_ 😉

**Comment by IsaacSchemm** [comment]
OK, that makes sense!
