### ISSUE TITLE
Will Chinese be supported?

### ISSUE THREAD

**Issue by psychelzh** [vjeantet/hugo-theme-docdock#177]
I need to write docs in Chinese recently, but Chinese is not currently supported. What should I do to make it suitable for Chinese?

**Comment by Pilskalns** [comment]
Ni hao @psychelzh,

First, it looks like Hugo itself should support the Chinese language ([`zh` language code, I guess](https://metacpan.org/pod/I18N::LangTags::List#{zh}-:-Chinese)).

* Have you tried setting the site language in the `config .toml/.yaml`?
* Do you have tried other themes where the Chinese works?

**Comment by psychelzh** [comment]
Thanks! Chinese does work. What I am wondering is that the shortcode `{{% note warning %}}` et. al. will use English words as the note title, and whether or not it could be changed as Chinese words.

**Comment by Pilskalns** [comment]
So you mean using chinese words specifically for part `notice warning`? I really don't think so, let me explain why:

Shortcodes are defined in the `themes/hugo-theme-docdock/layouts/shortcodes/`. For the shortcode the first parameter is the file basename - `notice` in this case. Second parameter for notice shortcode is the CSS class. To add chinese variant, then new file with chinese letter filename must be created as well as CSS class (not sure if CSS works with that, but who knows).

For fairness to other languages and maintainability, adding new language would mean doubling up shortcode files, CSS classes etc. etc. **THOUGH** if you really need chinese support, you can add custom shortcodes by copying files needed from `themes/hugo-theme-docdock/layouts/shortcodes/` to `layouts/shortcodes/` and then also adding necessary classes to the custom CSS file (please refer to docs).

**Comment by psychelzh** [comment]
Okay, I got it. Thank you for your careful and quick reply! I will try your suggestion later.

**Comment by Pilskalns** [comment]
Great, will close issue for now.
