### ISSUE TITLE
mermaid diagrams getting cropped and sized incorrectly

### ISSUE THREAD

**Issue by ivan-danilov** [vjeantet/hugo-theme-docdock#178]
I have cropping on my diagrams that does not happen with the last mermaid version (8.0.0) at the time.

I can make a PR with updated/minified mermaid.js if needed.

**Comment by Pilskalns** [comment]
Hi @ivan-danilov,

So you did local mermaid update and that solved the issues? As I am not familiar with the mermaid, could you do also test updated version in different scenarios before doing PR?

Other than that, would be nice to see your PR :)

**Comment by ivan-danilov** [comment]
Hi @Pilskalns 
See the PR above. I looked at it through my couple dozens of diagrams. Are there other ways I can test the version?

Maybe nice to add some diagram examples to the example site, what do you think?

**Comment by Pilskalns** [comment]
Yes, adding docs examples would be cool. Please add to the PR. They are (and will) be built in [this unique PR preview URL](https://deploy-preview-179--docdock.netlify.com/). So you can test how they will work on _production_. The link is also available when expanding checks section at PR page.

**Comment by ivan-danilov** [comment]
In fact, there are some examples in the shortcodes section (for preview URL it is [here](https://deploy-preview-179--docdock.netlify.com/shortcodes/mermaid/)). Totally missed them and they seem to work fine.

**Comment by ivan-danilov** [comment]
Added some more complicated example of a flowchart. Take a look, seems to render correctly.

**Comment by ivan-danilov** [comment]
I'm also trying to put another PR into mermaid here https://github.com/knsv/mermaid/pull/798

Just in case, I added another commit that updates mermaid.js once again with that PR included along with an example on the exampleSite. Hopefully, it will be useful as well.

**Comment by Pilskalns** [comment]
I've merged this into master with squash. You will have to pull again to avoid conflicts.

Thanks @ivan-danilov for your contribution!
