### ISSUE TITLE
big issue in theme demo, subtopics jump around in menu

### ISSUE THREAD

**Issue by gershomtripp** [vjeantet/hugo-theme-docdock#187]
I like the theme, but I'm hesitant to use it because of an issue in the [demo](https://docdock.netlify.com/). A large chunk of the menu skips to another part when I select "Configuration". The first image shows the menu before I select "Configuration", the second image shows it afterwards. You can see that the subtopics from "Content Organization" suddenly appear under "Getting Started".

Before selecting "Configuration":
<img width="284" alt="Bildschirmfoto 2019-04-11 um 16 22 37" src="https://user-images.githubusercontent.com/20071483/56026397-55b27a80-5d14-11e9-8262-92fd4f952c65.png">

After selecting configuration:
<img width="263" alt="Bildschirmfoto 2019-04-11 um 16 23 57" src="https://user-images.githubusercontent.com/20071483/56026403-59460180-5d14-11e9-9531-43baf3720bcc.png">

**Comment by ArchiveBase** [comment]
That's great even might mistake. @vjeantet when fix it, please also update the customization documentation about how to configure for jump to another main content part sub-menu list (i mean as above).
 just helpful such navigation when sub-menu content topic necessary to show other resources instead point or link to certain docs under that page as common way.

**Comment by ArchiveBase** [comment]
@gershomtripp couldnt say, its only issue in the demo. you can use the latest release

**Comment by Marthym** [comment]
Fixed on master
