### ISSUE TITLE
Extra "s" in aside menu entry titles

### ISSUE THREAD

**Issue by andrescs91** [vjeantet/hugo-theme-docdock#196]
When creating new content folders on the side menu, it automatically adds an extra "s" at the end of the name. I tried editing the htmls of every page, but now I see it overwrote all my changes and the extra "s" is back again. How can I fix that?

**Comment by dspaxton** [comment]
you probably want to add the following line to your config.toml:

pluralizelisttitles = false

**Comment by tarpdalton** [comment]
if you put a file called `_index.md` in the folder then you can name the content folders manually in the index file like this:
```
---
title: Title for my content folder
---
```

**Comment by andrescs91** [comment]
@dspaxton yeah, could figure this is what was missing and it worked perfectly, thanks!!
