### ISSUE TITLE
Flex Theme title of article(tag) is shown in the title

### ISSUE THREAD

**Issue by RalfKow** [vjeantet/hugo-theme-docdock#197]
If I choose the theme "flex" and I use the default tags.  In the created listpage, the title of all tags are not one after eachother but all in the header.

![image](https://user-images.githubusercontent.com/53481380/62352684-0d100e80-b509-11e9-9bf6-096cc4b0712f.png)

**Comment by timani** [comment]
+1 seeing the same. I haven't had time to dig into the template to see where this is being inject
