### ISSUE TITLE
Font Awesome Icons are not displayed on the index, working fine elsewhere

### ISSUE THREAD

**Issue by marteaurouge** [vjeantet/hugo-theme-docdock#20]
when loading http://themes.gohugo.io/theme/docdock/
it's happening, Font Awesome Icons are not displayed on the index, working fine elsewhere

I'm using Firefox and Chromium, it appears on both browsers.

**Comment by vjeantet** [comment]
Hello @marteaurouge can you elaborate on this issue ?

On index page, i can see a FA icon (the github icon).

Can you provide a screenshot ?

**Comment by marteaurouge** [comment]
you can see the problem here:
https://i.imgur.com/CKKI920.png

the font is not loading; lots of people gets this error:
https://stackoverflow.com/questions/14366158/font-awesome-not-working-icons-showing-as-squares

(i just don't get a square, cause i don't have the correct unicode loaded, the problem does not come from my computer being unable to render the font (i can see it on the official awesome website) and it's the same on my phone running android

but according to that stackoverflow thread it is the way you link the css, it's probably a bug,
but instead of using 
../fonts
you either have to link it from the root or include the http, really wierd bug, some even gave up and linked the font directly on the author's page

**Comment by marteaurouge** [comment]
and the icons works fine when testing the theme on http://docdock.netlify.com/

**Comment by marteaurouge** [comment]
found the error in the debugger:

>>downloadable font: download failed (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:3): bad URI or cross-site access not allowed source: https://themes.gohugo.io/theme/docdock/fonts/fontawesome-webfont.ttf?v=4.5.0

you can fix this by adding 
Header set Access-Control-Allow-Origin "*"
to your .htaccess

**Comment by vjeantet** [comment]
Ok the issue is related to the way you expose your website in combinaison with the baseUrl provided in config.toml. i'll open an issue on themes.gohugo.io

**Comment by vjeantet** [comment]
opened here : https://github.com/gohugoio/hugoThemes/issues/268

**Comment by vjeantet** [comment]
@marteaurouge, try to set a baseUrl with `//mywebsite.com` instead of `https://mywebsite.com`

**Comment by vjeantet** [comment]
Hugo thème fixed

**Comment by marteaurouge** [comment]
@vjeantet 
even without the https issue, the problem is still there:

if you publish your website with www.website.com the font won't work if a page is called with website.com (no www), and this is the case when people type your url (they usually won't add the www).

the opposite is also true, if you publish with website.com and then someone reach a page with www.website.com for some reason, the font won't work

the .htaccess code i posted is making it work

**Comment by vjeantet** [comment]
You are right.

Your solution will help users to solve such kind of issue.

As this is not related to docdock I will close this issue and let gohugo team its way.

Thanks again.

**Comment by marteaurouge** [comment]
thanks for your work on the theme!

**Comment by baranaydogan** [comment]
> found the error in the debugger:
> 
> > > downloadable font: download failed (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:3): bad URI or cross-site access not allowed source: https://themes.gohugo.io/theme/docdock/fonts/fontawesome-webfont.ttf?v=4.5.0
> 
> you can fix this by adding Header set Access-Control-Allow-Origin "*" to your .htaccess

I had this problem on a shared host when using Hugo v0.88.1 with the Syna theme v17.4. Editing the .htaccess file as above solved the problem.
