### ISSUE TITLE
Borders and Shadows not displayed for images

### ISSUE THREAD

**Issue by shazic** [vjeantet/hugo-theme-docdock#21]
Hi,  

I just replaced _Hugo Theme Learn_ with the theme _DocDock_ on my website https://invincible.site  

It is working great but I would like to report a minor issue related to images.  

In order to display shadows and borders for my images, I used the following markdown:  

```
![ImageTitle][page link]  

[page link]: /images/Image01.JPG?classes=border,shadow
```  

This is similar to what is described on your documentation under **Shortcodes > image** menu and it worked fine with the previous theme (Hugo theme Learn) as well.  

However, with DocDock, the borders and shadows are **not** displayed.  

I had tested this with the following browsers and none of them are showing the desired results:  
Safari,  
Firefox 53.0.3,  
Google Chrome 58.0.3029.110,  
Microsoft Edge 40.15063.0.0,  
IE 11 and  
Maxathon 4.4.8.1000.  

An _additional issue_ with **IE and Maxathon** web browsers is that theme variants (green and gold) are not reflected, even if they are selected through the config.toml (should I open a separate issue for this?).  

**Note**  
Here is a disclaimer about the changes to your CSS that I did. I do not believe that my changes should have an effect on the issues that I reported, but I am stating them for transparency:  

1. I used the template from your gold theme variant to create a theme that reflected the color theme of my website. The only things that I changed were the color values in the CSS variables.  
1. I changed the border-top of the footline to "none", so that it is not displayed on the pages.

**Comment by vjeantet** [comment]
can you try to update the theme and tell me i you still have the issue ?

i think this is related to a fixed issue 4 days ago.

ref : https://github.com/vjeantet/hugo-theme-docdock/commit/1af2a78989cc17e90fe3f3494e2dda05be2937e5

**Comment by shazic** [comment]
Thank you. 

I must have missed the fix by a whisker. 
With the latest update, it is _working perfectly_.

(Before opening the ticket, I had somehow failed to realize that issue #17 was directly related to this one. My bad!)

**Comment by vjeantet** [comment]
May i reference your website in the docdock documentation ? I really like your website !

**Comment by vjeantet** [comment]
And can you send a PR with your theme black and white variants ?

**Comment by shazic** [comment]
Sure, you can reference my website. I am glad you liked my work. 

I will shortly send you the Pull Request with the theme variant.
