### ISSUE TITLE
using theme

### ISSUE THREAD

**Issue by MAlexGR** [vjeantet/hugo-theme-docdock#210]
Please clarify the :

> Change following config.toml line as needed, depending on method above:
> `theme = "<hugo-theme-docdock-dir-name>"`

 Where is the theme? I did initialize my site with `hugo new site` and added docdock as sumodule, according to instructions.

What should I write there? (in config.yaml):

- `theme="hugo-theme-docdock-dir-name"` (I mean litterally?)
- `theme="themes/docdock"`?
- `theme="themes/docdock/exampleSite"`?
- `theme="themes/docdock/exampleSite/themes"`?
- ...

So far I'm always getting the: `Error: module "themes/docdock/exampleSite" not found; either add it as a Hugo Module or store it in "/home/<user>".: module does not exist` and its variants

Please help!

Alex

**Comment by EmmanuelJeanBriand** [comment]
Try `theme="docdock"`
