### ISSUE TITLE
Setting the themeVariant in config.toml does not have any effect

### ISSUE THREAD

**Issue by protenhan** [vjeantet/hugo-theme-docdock#26]
Hi, 

for me setting the ```themeVariant``` in the config.toml does not have any effect. Im always seeing the blue default theme.

My config.toml:
```
DefaultContentLanguage = "en"
theme = "docdock"
themeVariant = "gray"
```

im running hugo 0.24.1
`Hugo Static Site Generator v0.24.1 darwin/amd64 BuildDate: 2017-06-26T09:33:45+02:00`

Any suggestions on what I'm doing wrong are highly appreciated.

**Comment by vjeantet** [comment]
Can you confirm this issue with chrome or Firefox ?

**Comment by MatthiasKammerlohr** [comment]
Internet explorer does not support css var() variables which are used in themes:

https://developer.mozilla.org/de/docs/Web/CSS/var

Just replace it with normal css colors in an overwritten themeVariant css file. Worked for me!

**Comment by protenhan** [comment]
@vjeantet I have tested it with Safari 10.1.1, Chrome 59.0.3071.115 and Firefox 54.0.1 . I'm always getting the blue version. For the time being I already started with what @MatthiasKammerlohr suggested and overwrote the default colours in teh theme.css file.

**Comment by vjeantet** [comment]
Hello @protenhan, can you give me a link to your repo ?

**Comment by vjeantet** [comment]
can you try  to insert `[params]` before your themeVariant

```
DefaultContentLanguage = "en"
theme = "docdock"
[params]
themeVariant = "gray"
```

**Comment by ringods** [comment]
@vjeantet setting it in the `[params]` section fixed it for me. Tnx.

**Comment by protenhan** [comment]
Yes, this also works for me 👍 Thank you for your help!

**Comment by RobKraft** [comment]
Adding [params] before themeVariant fixed it for me.  Wow, wasted 2 hours on this.
For clarification for others, the file to change this in is the config.toml that is in the root of your site, not one in any of the themes subfolders.
