### ISSUE TITLE
New content structure incompatible with uglyURLs = true

### ISSUE THREAD

**Issue by SiamKreative** [vjeantet/hugo-theme-docdock#27]
Hey there! _Bonjour_!

Have you tried using the theme with `uglyURLs` set to `true`? The problem is that when setting this option to true, the parent menu will not be open when browsing a child page.

Cheers

**Comment by SiamKreative** [comment]
@vjeantet I actually tried on the exampleSite and it works fine. For some reason, my current setup does not add the class `.parent` on the `<li>` (alongside the class `.dd-item`).

I am investigating the issue.

**Comment by SiamKreative** [comment]
- Hugo version 0.24 (windows/amd64)
- Able to replicate the issue using the exampleSite

![image](https://user-images.githubusercontent.com/1778633/27904776-00d913dc-6268-11e7-8e68-eb3d7ccabbc3.png)

**Comment by vjeantet** [comment]
Good catch ! this will be fixable with recent @bep addition to the next hugo version : https://github.com/gohugoio/hugo/issues/3591

.IsAncestor will be used instead of the hasPrefix

**Comment by bep** [comment]
And I plan to release that new Hugo version tomorrow.

**Comment by SiamKreative** [comment]
Fantastic job guys! Can't wait to install the new version.
