### ISSUE TITLE
All fonts changed to italic

### ISSUE THREAD

**Issue by j2scode** [vjeantet/hugo-theme-docdock#28]
Hi! Great theme!

I'm running into a situation with my fonts and I was hoping that I could ask you what I hope is a fairly straight forward question that should take you 2 secs.  I'm in the process of doing some customization and have successfully modified some aspects of the color palette.  My challenge now is that all the fonts are italic and I am not able to find the css script that is assigning the italic fonts.  I've checked the themes css (thoroughly) but no luck identifying where the appropriate change needs to be made.  Could you please advise me on this issue?

**Comment by vjeantet** [comment]
Hello

   Give me a link to your website or repo I'll have a look

**Comment by j2scode** [comment]
Actually, it turned out to be a non-problem. I was viewing the site in R studio's view pane.  Rendering it to a domain resolved the issue.  Thanks for jumping on this so quickly.
