### ISSUE TITLE
Reverse alpha sort

### ISSUE THREAD

**Issue by vielmetti** [vjeantet/hugo-theme-docdock#29]
I'm trying to sort out how to sort entries, so that the most recent documents end up at the top.

The hardest way to do this is with the 'weight=' parameter, though I could do it by computing a weight for the first entry at some large number and then count backwards.

By default the sort order is a-z,  my documents naturally want to sort z-a, I don't see an easy way to do that in a directive.

**Comment by vjeantet** [comment]
I just fixed an issue about menu ordering with weight.
https://github.com/vjeantet/hugo-theme-docdock/issues/25

can you try again and tell me if the issue is still there ?

**Comment by vielmetti** [comment]
Hi @vjeantet - the menus seem to order as expected
