### ISSUE TITLE
multi language

### ISSUE THREAD

**Issue by icf20** [vjeantet/hugo-theme-docdock#3]
what needs to be changed in the theme to make it multi language ?

edit everything look to work nice except the _index.md & _header.md

**Comment by vjeantet** [comment]
Hello @icf20 , can you fork and try what you propose, i will then help you with _index.md & _header.md

**Comment by gwleclerc** [comment]
According to https://gohugo.io/content/multilingual/ it's not a big deal to make a theme multilingual

**Comment by vjeantet** [comment]
reopened because _index.md and _header issue is still open

**Comment by icf20** [comment]
never mind i figured out that is better to run this like 4 separate projects one for each language so is easier to maintain

**Comment by marteaurouge** [comment]
is the multi language still planned, or is running several projects separately more simple?

**Comment by vjeantet** [comment]
labels used but the theme are localized (FR and EN) , not sure about the multi language hugo, i tried to follow gohugo documentation but i failed.

* see localized labels here : https://github.com/vjeantet/hugo-theme-docdock/tree/master/i18n

I have no estimated date to fully support (and understand) it.

**Comment by xxxtonixxx** [comment]
Hi @vjeantet I have used your theme to a project (https://github.com/qontu/ngx-inline-editor/pull/79) and I have modified it to add multilingual support, if you want I can do a PR to add my changes and a small setup guide 😄 

An image of language menu 😉 
![image](https://user-images.githubusercontent.com/7110786/28383428-6782428a-6cc1-11e7-8b76-d757c3ec9c2d.png)

URL of the multilingual docs
https://xxxtonixxx.github.io/ngx-inline-editor/en/

Thanks for your work in this hugo theme, it's awesome! 👍

**Comment by vjeantet** [comment]
¡ Ola !

Yes please send your PR with your implementation and your doc, i'll merge it

Thanks a lot

**Comment by matcornic** [comment]
Hey @vjeantet . I implemented this feature in v2 of Learn. Feel free to cherry pick the code.

**Comment by xxxtonixxx** [comment]
It was implemented by @jose-oc in https://github.com/vjeantet/hugo-theme-docdock/pull/97. This issue can be closed! :tada: :smile:
