### ISSUE TITLE
About the search engine

### ISSUE THREAD

**Issue by vielmetti** [vjeantet/hugo-theme-docdock#30]
The documentation states:

```
ABOUT THE SEARCH ENGINE

Nothing to do on your side. :-)

Docdock theme uses the last improvement available in hugo version 20+ to generate a json index file ready to be consumed by lunr.js javascript search engine.
```

Where is this JSON file located? I'm not seeing it in my installation, and the search engine doesn't seem to be working at the moment.

**Comment by vielmetti** [comment]
Aha, the index was throwing errors, and so some index didn't get built; but I still am puzzled where it gets put!

**Comment by vielmetti** [comment]
Sorry, answering my own question, there's an index.json created when you build the site with hugo; I was running "hugo server" and of course those internally generated files don't show up in the filesystem.

**Comment by vjeantet** [comment]
Hello

   The documentation pages should be completed, with your experience. In case someone figure the same "issue" to not let him waste time on this
