### ISSUE TITLE
Content structure can conflict with taxonomies

### ISSUE THREAD

**Issue by ringods** [vjeantet/hugo-theme-docdock#32]
I create this folder structure:

```
config.toml
content
   \- tools
        |- _index.md   (title = "Tools")
        |- main-tool.md
        |- api-management
        |       |- _index.md   (title = "API Management")
        |       \- tool1.md
        \- user-management
                |- _index.md   (title = "User Management")
                \- tool2.md
```

When running Hugo (0.24.1) locally with the Dockdock theme, I get this console output:

```
$ hugo
Started building sites ...
Built site for language en:
0 draft content
0 future content
0 expired content
9 regular pages created
7 other pages created
0 non-page files copied
1 paginator pages created
0 tools created
total in 16 ms
```

The rendered site contains the "Tools" section with all my links are directly listed under it. No subsections "API Management" and "User Management". The generated URLs are correct though:

* <site>/tools/main-tool/index.html
* <site>/tools/api-management/tool1/index.html
* <site>/tools/user-management/tool2/index.html

The breadcrumbs at the top of each page list `Wiki > Tools > <name of tool here>`, also not the subsection.

Eventually I found out that I have an overlap between my content organisation and a configured taxonomy. Here was my taxonomy section from `config.toml`:

```
[taxonomies]
tool = "tools"
```

After disabling this, the site rendered correctly again. Would it be possible to generate an error, or render a big warning when such an overlap exists?

**Comment by vjeantet** [comment]
Hello @ringods , this is a know and accepted limitation.

An Hugo issue exist to improve warning message about this in logs. see https://github.com/gohugoio/hugo/issues/3679
