### ISSUE TITLE
top level pages without children have open/collapse icon

### ISSUE THREAD

**Issue by hyOzd** [vjeantet/hugo-theme-docdock#36]
As you can see on the homepage of docdock theme, top level pages that have no children still show an open/collapse arrow icon.

![docdockbug](https://user-images.githubusercontent.com/1479166/28114436-919eb156-6709-11e7-92f0-fa62b19bc287.png)

Edit: By the way I create a top level page as a folder with _index.md file. Any .md under the 'content/' doesn't show up in the sidebar.

**Comment by vjeantet** [comment]
Real bug ! I will fix this for tomorrow
