### ISSUE TITLE
[Question] [Performance] Concatenate and minify JavaScript dependencies?

### ISSUE THREAD

**Issue by SiamKreative** [vjeantet/hugo-theme-docdock#43]
Hi there,

Should all dependencies be concatenated? 

- \hugo-theme-docdock\static\js\clipboard.min.js
- \hugo-theme-docdock\static\js\featherlight.min.js
- \hugo-theme-docdock\static\js\highlight.pack.js
- \hugo-theme-docdock\static\js\horsey.js
- \hugo-theme-docdock\static\js\html5shiv-printshiv.min.js
- \hugo-theme-docdock\static\js\hugo-learn.js
- \hugo-theme-docdock\static\js\jquery-2.x.min.js
- \hugo-theme-docdock\static\js\learn.js
- \hugo-theme-docdock\static\js\list.txt
- \hugo-theme-docdock\static\js\lunr.min.js
- \hugo-theme-docdock\static\js\modernizr.custom.71422.js
- \hugo-theme-docdock\static\js\search.js

If all of those dependencies are required for the theme to function, I would suggest to concenate and minify those using gulp / grunt or npm directly.

I would only exclude jQuery from being included in the bundle as some users would like to serve it from [Google CDN](https://developers.google.com/speed/libraries/#jquery). It could be very handy to have a setting to override where is jQuery loaded from.

Cheers

**Comment by SiamKreative** [comment]
Hi @vjeantet,

What's the best way to apply those optimizations just for my documentation site? I don't like the idea of overriding `footer.html` (copying the file from themes\hugo-theme-docdock\layouts\partials) because it contains more than the script.

Would it be a good idea to split the scripts from`footer.html` and move them into its own file like `scripts.html`? That way, anyone can easily override the included scripts?

What's your take on this?

Cheers

**Comment by stp-ip** [comment]
Not sure such optimization is really needed. With http/2 concatenation leads to worse performance due to cache invalidation, when one script changes. All scripts are loaded with almost no overhead due to http/2.

Minification could still be something interesting. This can easily be done via a PR I assume.

For overwriting specific scripts and where they are loaded from. As far as best practice goes:
* load them locally first
* make it configurable via file or setting to load from somewhere else.

**Comment by SiamKreative** [comment]
Thanks for getting back to me @stp-ip. Unfortunately, not everyone is using http/2 which means it would be good to concatenate / minify those assets.

But instead of doing the optimizations for everyone (which could  be counter productive for those using http/2, as you pointed out), I will submit a PR to move the scripts to their own partial file. That way, we increase flexibility for developers.

**Comment by SiamKreative** [comment]
FYI The https://github.com/vjeantet/hugo-theme-docdock/pull/53 has been merged, allowing more flexibility for developers
