### ISSUE TITLE
About Images documentation is blank

### ISSUE THREAD

**Issue by tblom** [vjeantet/hugo-theme-docdock#50]
When looking for documentation about images I found [a blank page](https://themes.gohugo.io/theme/docdock/create-page/page-images/) linked from the "About images" menu item under "Create Page".

https://themes.gohugo.io/theme/docdock/create-page/page-images/

I was hoping to find docs about a simple way to center an image with a caption that is also centered - would seem handy in a documentation theme.

**Comment by vjeantet** [comment]
thanks, fixed
