### ISSUE TITLE
Naming a page button result in wrong display

### ISSUE THREAD

**Issue by MangelMaxime** [vjeantet/hugo-theme-docdock#55]
When setting a page title to button ,I got the following result:

![image](https://user-images.githubusercontent.com/4760796/29190645-3d2bbba4-7e1b-11e7-9c78-8bfce5f24a7b.png)

I don't really understand the reason...

**Comment by ronaldscott** [comment]
@MangelMaxime can you elaborate on what behavior you consider inappropriate?

**Comment by MangelMaxime** [comment]
@ronaldscott The yellow color on the `b` and `u` letters.

**Comment by matcornic** [comment]
It's because your searched for "bu". Click on the cross in the search field and yellow should disappear

**Comment by pepc** [comment]
To fix it, just remove the `b` and `u` letters from the search box on the top left.

**Comment by vjeantet** [comment]
:) thanks @matcornic

**Comment by MangelMaxime** [comment]
Ah yes, I forgot to answer.

Yes the problems was the search results.. Sorry.
