### ISSUE TITLE
Is it possible to start with the menu unfolded?

### ISSUE THREAD

**Issue by wsw70** [vjeantet/hugo-theme-docdock#6]
When opening the site, the submenu items are hidden under their parents and unfold when clicking on the parent page.

Is it possible to configure teh site so that all sub-entries of the menu are unfolded at start (and therefore the structure of the site is immediately visible)?

**Comment by vjeantet** [comment]
Hello @wsw70 not sure about this behavior, if there are too many menus it becomes useless i think.

You can use the [children shortcode](https://docdock.netlify.com/shortcode/children/) to display the structure on your homepage

Or maybe use the icon on right of each menu item to unfold them when needed.... have a look on https://docdock.netlify.com

What do you think ?

**Comment by wsw70** [comment]
Thanks @vjeantet for following up. I was actually thinking about a way to configure such behaviour, rather then to have it as a norm.

Specifically, I have **one** item of the menu I would like to keep open (except if someone folds it up) as it contains information which needs to be directly accessible (one level under the root).

I agree that having it for all could be a problem - thus the ability to configure on a case by case basis

I saw that `{{% children  %}}` could be a solution but I do not see how it could be used for a single entry of the menu (short of hardcoding it in the menu)

**Comment by vjeantet** [comment]
> Specifically, I have one item of the menu 

I like this idea, an param in page's frontmatter could be a solution. 

example 
```
[menu.main]
identifier = "getting-start"
unfolded = true
```

is `unfolded` meaningfull ?

**Comment by vjeantet** [comment]
argh... we have to wait this Hugo PR https://github.com/spf13/hugo/pull/3277 to set params on menuitems

**Comment by vjeantet** [comment]
another option  is to reference the menu identifier to keep open, in the site configuration file (config.toml)

**Comment by vjeantet** [comment]
done have a look here : https://docdock.netlify.com/organisation/#unfolded-menu-entry-by-default

**Comment by wsw70** [comment]
That's fantastic, thanks a lot
