### ISSUE TITLE
show page toc at top of the page

### ISSUE THREAD

**Issue by muffmolch** [vjeantet/hugo-theme-docdock#60]
Like in media wiki I want to show the toc of the current page at the top of that page.

I tried a lto of stuff, but the toc os always empty! For testing reasons I put 

    {{ .TableOfContents }}

into the default layouts, but that doesn't work... (the toc is emtpy)

**Comment by muffmolch** [comment]
I have to use
{{ .Page.TableOfContents }}

**Comment by Pilskalns** [comment]
Hi @muffmolch. Where did you tried `{{ .TableOfContents }}` function? It won't work inside markdown files. This would work only in `.html` (layout) files.

Have to edit theme (override theme layouts with your own) for this to work.
You could create theme boolean variable `showToc` and if true then include it within `layouts/_default/single.html`.

**Comment by SevenSnows** [comment]
Strangely I have HTML content in the Raw Source of the page for TableOfContents; But like Pikskalns display: none; and hence it does not show.

**Comment by vjeantet** [comment]
fixed
use `toc` shortcode in your page

`{{%toc/%}}`
