### ISSUE TITLE
Footer partial generator extreme amount of whitespace

### ISSUE THREAD

**Issue by GeertvanHorrik** [vjeantet/hugo-theme-docdock#61]
In my pages (complex website with reference documentation) I have about 20k lines of whitespace. This is caused by the footer.html (<div id="navigation").

Any idea how to prevent this from happening?

**Comment by GeertvanHorrik** [comment]
By removing that part from the footer, site generation goes from 48 => 24 seconds. Files also get half the size.

**Comment by Pilskalns** [comment]
I see Hugo has wonderful builtin function which could be as wide improvement to minify rendered HTML across all themes. No external build tools then required.

https://gohugo.io/templates/introduction/#whitespace

**Comment by Pilskalns** [comment]
@GeertvanHorrik can you try this e371ac0?

**Comment by GeertvanHorrik** [comment]
Doesn't seem to work. It's the spaces in front of the code that are the culprit:

![image](https://user-images.githubusercontent.com/1246444/30534873-57815956-9c60-11e7-933a-5f19d19d3249.png)

**Comment by Pilskalns** [comment]
Yes, those spaces I "compressed". I did changes only inside `<div id="navigation">..</div>`. So many spaces should come from one of loops (range).

1. You sure my commit is in effect for local copy you try?
2. Maybe you have this file override outside theme directory?
3. Restart Hugo, live-preview can fail update template files (if you use live-preview).
4. Look for errors when starting local Hugo server.
and...
5. Can you locate from where exactly in `.html` layout those extra whitespaces come from?

**Comment by GeertvanHorrik** [comment]
Using this seems to fix it:

```
<div id="navigation">
<!-- Next prev page -->
{{with ($.Scratch.Get "prevPage")}}<a class="nav nav-prev" href="{{.URL}}" title="{{.Title}}"> <i class="fa fa-chevron-left"></i></a>{{end}}
{{with ($.Scratch.Get "nextPage")}}<a class="nav nav-next" href="{{.URL}}" title="{{.Title}}" style="margin-right: 0px;"><i class="fa fa-chevron-right"></i></a>{{end}}
</div>
```

**Comment by Pilskalns** [comment]
@GeertvanHorrik please check-out this [compress-html-whitespace](https://github.com/Pilskalns/hugo-theme-docdock/tree/compress-html-whitespace) and check result

**Comment by GeertvanHorrik** [comment]
I think it's the spaces *in front of the template codes* that are the issue. Your fixes don't seem to fully solve the issue:

![image](https://user-images.githubusercontent.com/1246444/30540892-45029c5e-9c79-11e7-8d1f-e5f46ea8b2aa.png)

**Comment by GeertvanHorrik** [comment]
After some more tests, it already looks a lot cleaner and files have gone from 700kb => 360kb. 

![image](https://user-images.githubusercontent.com/1246444/30541911-8bd3b902-9c7d-11e7-8ac8-2191d3fd4727.png)

**Comment by GeertvanHorrik** [comment]
As a final experiment, I've opened the menu.html partial in notepad++, select all, shift + tab until there is no more indentation. Now the file is 320kb, which is a lot better.

**Comment by Pilskalns** [comment]
Those _blank lines_ in https://github.com/vjeantet/hugo-theme-docdock/issues/61#issuecomment-330163006 are from template lines, which has Hugo template code, but does not produce any actual output.

Removing whitespace before `<a>` tag would only remove from that line. It can't produce that amount of _blank lines_, and also have different indentation. Here all lines `<li>`, `<a ...` and `</li>` have same indent space.

Removing all, all, all odd spaces (minifying it) in template is not practical as it makes code and HTML hard to read. To do that for production level use tools for this purpose. I.e. something automated like Grunt or even SaaS like Netlify.

**Comment by Pilskalns** [comment]
@GeertvanHorrik I suggest this to be closed.

**Comment by GeertvanHorrik** [comment]
Fully agree, thanks for fixing!
