### ISSUE TITLE
Navigation without unique urls?

### ISSUE THREAD

**Issue by GeertvanHorrik** [vjeantet/hugo-theme-docdock#62]
As you can see on this page:

http://docs.catelproject.com/vnext/reference/catel.core/

![image](https://user-images.githubusercontent.com/1246444/30249773-4c507076-9643-11e7-867d-80d1ca33effa.png)

The menu system gets a bit weird. I think this is because it's not using full urls to determine the expanded / selected nodes.

**Comment by vjeantet** [comment]
fixed. UniqueID() missuse @see https://github.com/gohugoio/hugo/issues/2861

**Comment by GeertvanHorrik** [comment]
Works great, thanks!
