### ISSUE TITLE
Style for images and videos might be too intrusive

### ISSUE THREAD

**Issue by GeertvanHorrik** [vjeantet/hugo-theme-docdock#86]
This style:

```
#body img, #body .video-container {
    margin: 3rem auto;
    display: block;
    text-align: center;
}
```

results in stuff like this:

![image](https://user-images.githubusercontent.com/1246444/31319628-583f9012-ac67-11e7-822b-ae1a57e9454e.png)

**Comment by GeertvanHorrik** [comment]
For now I've fixed it ty allowing a custom theme-customization.css. Maybe it's a good idea to implement that in the header anyway?

**Comment by vjeantet** [comment]
Hello, can you show you md code ?

you can add a "inline" class to your img to get image displayed without margins.

`class="inline"`

**Comment by vjeantet** [comment]
if you are using a img md notation `![]()` add `classes=inline` at the end of your image path
example : 

```
![agence](https://github.com/vjeantet/vjeantet.fr/raw/master/static/images/sgthon/C.jpg?classes=inline)
```

**Comment by GeertvanHorrik** [comment]
Works great, thanks!
